### ISSUE TITLE
Organize UI elements.

### ISSUE THREAD

**Issue by remuladgryta** [remuladgryta/constellationgenerator#8]
I'm no web designer but there is probably a better way to organize the input controls.

Maybe organize into groups? Generator inputs, drawing controls, save-load, and the drawing itself are four distinct groups that come to mind.

If someone who knows more css-fu than me would like to take a look at this, it would be much appreciated.

**Comment by lordhi** [comment]
I'm working on this now, might take a while though as I'm not hugely familiar with html and css anymore, should hopefully have a prototype working tomorrow at least

**Comment by remuladgryta** [comment]
Currently there are mixed tabs and spaces indenting the code. I'm about to fix it but I suggest you wait with working on anything until it's up. Pulling that commit will probably cause merge conflicts for you.

**Comment by lordhi** [comment]
I just actually did that in my local copy
I can try to finish up with this in a few minutes and put in a PR with that fixed?

**Comment by remuladgryta** [comment]
I just pushed the indentation fix. 2 spaces per indentation level has been arbitrarily decided on. Sorry for the inconvenience if it messes up things for you.

**Comment by lordhi** [comment]
Nevermind that...
Getting the js to play nicely with html elements is more difficult than anticipated

**Comment by lordhi** [comment]
Nah it's fine, I can change that on mine in around a second anyway

**Comment by remuladgryta** [comment]
Merged UI improvements in 9cbbc26
